server:
  port: 8003
  error:
    include-message: always

spring:
  application:
    name: iot-user-service
  main:
    web-application-type: reactive
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017
      database: iot

jwt:
  secret: "[ a-zA-Z0-9._ ]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://iot-discovery-service:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: DEBUG
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG