server:
  port: 8003
  error:
    include-message: always

spring:
  application:
    name: iot-user-service
  datasource:
    url: jdbc:postgresql://postgresql:5432/iot
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: "[ a-zA-Z0-9._ ]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://iot-discovery-service:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
