spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017
      database: iot


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

