server:
  port: 8003
  error:
    include-message: always
  netty:
    connection-timeout: 5000

spring:
  application:
    name: iot-user-service
  main:
    web-application-type: reactive
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://mongo:mongo@mongodb:27017
      database: iot

jwt:
  secret: "[ a-zA-Z0-9._ ]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://iot-discovery-service:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
