apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-discovery-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: iot-discovery-service
  template:
    metadata:
      labels:
        app: iot-discovery-service
        team: iot-discovery-service
    spec:
      containers:
      - name: iot-discovery-service
        image: alexdragnea/disertatie-iot-discovery-service:latest
        resources:
          limits:
            memory: 1024Mi
            cpu: 1024m
          requests:
            cpu: 768m
            memory: 768Mi
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 30
          periodSeconds: 5