apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-bridge-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: iot-bridge-service
  template:
    metadata:
      labels:
        app: iot-bridge-service
    spec:
      containers:
      - name: iot-bridge-service
        image: alexdragnea/disertatie-iot-bridge-service:latest
        resources:
          limits:
            memory: 1024Mi
            cpu: 1024m
          requests:
            cpu: 768m
            memory: 768Mi
        ports:
        - containerPort: 8001
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 5