apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-coreservice
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: iot-coreservice
  template:
    metadata:
      labels:
        app: iot-coreservice
    spec:
      containers:
      - name: iot-coreservice
        image: alexdragnea/disertatie-iot-coreservice:latest
        resources:
          limits:
            memory: 768Mi
            cpu: 512m
          requests:
            cpu: 256m
            memory: 512Mi
        ports:
        - containerPort: 9000
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9000
          initialDelaySeconds: 100
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9000
          initialDelaySeconds: 100
          periodSeconds: 5