apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-user-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: iot-user-service
  template:
    metadata:
      labels:
        app: iot-user-service
    spec:
      containers:
      - name: iot-user-service
        image: alexdragnea/disertatie-iot-user-service:latest
        resources:
          limits:
            memory: 1024Mi
            cpu: 1024m
          requests:
            cpu: 512m
            memory: 512Mi
        ports:
        - containerPort: 8002
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8002
          initialDelaySeconds: 100             # Increase delay to give the container more time to be ready
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3