apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-discovery-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: iot-discovery-service
  template:
    metadata:
      labels:
        app: iot-discovery-service
        team: iot-discovery-service
    spec:
      containers:
      - name: iot-discovery-service
        image: alexdragnea/disertatie-iot-discovery-service:latest
        resources:
          limits:
            memory: 512Mi
            cpu: 512m
          requests:
            cpu: 256m
            memory: 256Mi
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60             # Increase delay to give the container more time to be ready
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 60             # Increase delay to give the container more time to be ready
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3