apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-gateway-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: iot-gateway-service
  template:
    metadata:
      labels:
        app: iot-gateway-service
    spec:
      containers:
      - name: iot-gateway-service
        image: alexdragnea/disertatie-iot-gateway-service:latest
        env:
        resources:
          limits:
            memory: 768Mi
            cpu: 1024m
          requests:
            cpu: 512m
            memory: 512Mi
        ports:
        - containerPort: 8888
        readinessProbe:
          httpGet:                           # Use httpGet but specify the scheme as HTTPS
            path: /actuator/health
            port: 8888
            scheme: HTTPS                    # Add this line to indicate HTTPS
          initialDelaySeconds: 10            
          periodSeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 2