apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-gateway-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: iot-gateway-service
  template:
    metadata:
      labels:
        app: iot-gateway-service
    spec:
      containers:
      - name: iot-gateway-service
        image: alexdragnea/disertatie-iot-gateway-service:latest
        resources:
          limits:
            memory: 1024Mi
            cpu: 1024m
          requests:
            cpu: 768m
            memory: 768Mi
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:                           # Use httpGet but specify the scheme as HTTPS
            path: /actuator/health
            port: 8888
            scheme: HTTPS                    # Add this line to indicate HTTPS
          initialDelaySeconds: 30             # Increase delay to give the container more time to start
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3

        readinessProbe:
          httpGet:                           # Use httpGet but specify the scheme as HTTPS
            path: /actuator/health
            port: 8888
            scheme: HTTPS                    # Add this line to indicate HTTPS
          initialDelaySeconds: 30             # Increase delay to give the container more time to be ready
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3