apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-core-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: iot-core-service
  template:
    metadata:
      labels:
        app: iot-core-service
    spec:
      containers:
      - name: iot-core-service
        image: alexdragnea/disertatie-iot-core-service:latest
        resources:
          limits:
            memory: 768Mi
            cpu: 768m
          requests:
            cpu: 512m
            memory: 512Mi
        ports:
        - containerPort: 8002
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8002
          initialDelaySeconds: 60             # Increase delay to give the container more time to be ready
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8002
          initialDelaySeconds: 60             # Increase delay to give the container more time to be ready
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3