global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'iot-discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['iot-discovery-service:8761']

  - job_name: 'iot-bridge-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['iot-bridge-service:8001']

  - job_name: 'iot-core-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['iot-core-service:8002']

  - job_name: 'iot-gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['iot-gateway-service:8888']

  - job_name: 'iot-user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['iot-user-service:8003']