apiVersion: v1
kind: Service
metadata:
  name: iot-user-service
  labels:
    micrometer-prometheus-discovery-http: 'true'  # Label for HTTP scraping
spec:
  selector:
    app: iot-user-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      name: metrics