apiVersion: v1
kind: Service
metadata:
  name: iot-bridge-service
  labels:
    micrometer-prometheus-discovery: 'true'
spec:
  selector:
    app: iot-bridge-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      name: metrics