apiVersion: v1
kind: Service
metadata:
  name: iot-discovery-service
  labels:
    micrometer-prometheus-discovery: 'true'
spec:
  type: LoadBalancer
  selector:
    app: iot-discovery-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
      name: metrics