apiVersion: v1
kind: Service
metadata:
  name: iot-gateway-service
  labels:
    micrometer-prometheus-discovery: 'true'
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    name: metrics
  selector:
    app: iot-gateway-service