apiVersion: v1
kind: Service
metadata:
  name: iot-gateway-service
  labels:
    micrometer-prometheus-discovery-https: 'true'  # Label for HTTPS scraping
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888            # This is the port exposed by the service
      targetPort: 8888      # This is the port the container listens on for your application
      name: metrics         # Name for this port
  selector:
    app: iot-gateway-service
