apiVersion: v1
kind: Service
metadata:
  name: iot-core-service
  labels:
    micrometer-prometheus-discovery: 'true'
spec:
  selector:
    app: iot-core-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      name: metrics
        