apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iot-microservices-http-monitor
spec:
  endpoints:
    - interval: 15s
      path: /actuator/prometheus
      port: metrics    
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      micrometer-prometheus-discovery-http: 'true' 
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: iot-gateway-https-monitor
spec:
  endpoints:
    - interval: 15s
      path: /actuator/prometheus
      port: metrics  # Replace with the correct port name if different
      scheme: https  
      tlsConfig:
        insecureSkipVerify: true  # Set to true for skipping TLS verification
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      micrometer-prometheus-discovery-https: 'true'  # Match HTTP services

