server:
  port: 8002
  error:
    include-message: always

influxdb:
  url: http://influxdb:8086
  token: h8vYj604xa2oMASapwTq-rwyVR6_INHZCLKwdfGxzggeJWOtFcyR5jCYxInROotkv-yCWg1p5NQL-ANuSb2wUg==
  organization: upb
  bucket: iot-event-bucket

spring:
  application:
    name: iot-core-service
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://iot-discovery-service:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

