server:
  port: 8002
  error:
    include-message: always
  netty:
    connection-timeout: 5000
    response-timeout: 5000
    max-connections: 1000



influxdb:
  url: http://influxdb:8086
  token: tDdAyUYuIau7IFtxvLQ23gIoprJ5x1-xhJ7iN0Na8Sq_29rCDPiG-lEnTcDw9-CQ4M3IFyTSXhuC0Thf5pUy4g==
  organization: upb
  bucket: iot-measurement-bucket



spring:
  application:
    name: iot-core-service
  main:
    web-application-type: reactive
  data:
    redis:
      host: redis-service
      port: 6379
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: ro.upb.iotcoreservice.kafka.deserializer.MeasurementMessageDeserializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://iot-discovery-service:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

cache:
  caffeine:
    initialCapacity: 100
    maximumSize: 500
    expireAfterWriteMinutes: 10
    weakKeys: true
    recordStats: true


redis:
  deduplicationExpiry: 3600

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
