server:
  port: 8002
  error:
    include-message: always


influxdb:
  url: http://influxdb:8086
  token: tDdAyUYuIau7IFtxvLQ23gIoprJ5x1-xhJ7iN0Na8Sq_29rCDPiG-lEnTcDw9-CQ4M3IFyTSXhuC0Thf5pUy4g==
  organization: upb
  bucket: iot-measurement-bucket

spring:
  application:
    name: iot-core-service
  main:
    web-application-type: reactive
  data:
    mongodb:
      authentication-database: admin
#      uri: mongodb://localhost:27017
      uri: mongodb://mongo:mongo@mongodb:27017
      database: iot
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      session-timeout-ms: 10000
      request-timeout-ms: 30000
      max-poll-interval-ms: 300000
      max-poll-records: 500
      concurrency: 3

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://iot-discovery-service:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

cache:
  caffeine:
    initialCapacity: 100
    maximumSize: 500
    expireAfterWriteMinutes: 10
    weakKeys: true
    recordStats: true


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web.reactive.socket: DEBUG
    ro.upb.iotcoreservice.websocket: DEBUG