server:
  port: 9000
  error:
    include-message: always

spring:
  application:
    name: iot-core-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://iot-discovery-service:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

