apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: client
      port: 9092
      targetPort: kafka
      protocol: TCP
  type: ClusterIP