server:
  port: 8888
  error:
    include-message: always

spring:
  jmx:
    enabled: true
  application:
    name: iot-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        connect-timeout: 6000  # ⏳ 6s connection timeout (slightly higher than Service A)
        response-timeout: 12000  # ⏳ 12s total response timeout
        pool:
          max-connections: 2000  # 🚀 Allow 2000 concurrent connections
          eviction-interval: 30000ms  # 🧹 Clean up stale connections every 30s
          acquire-timeout: 5000  # ⏳ Max wait time for a free connection: 5s
          type: FIXED
        ssl:
          handshake-timeout: 8000ms  # 🤝 8s for SSL handshake (slightly higher than Service A)
          close-notify-flush-timeout: 200ms
          close-notify-read-timeout: 0ms
      routes:
        - id: iot-core-ws
          uri: lb:ws://iot-core-service/ws
          predicates:
            - Path=/ws
            - Header=Upgrade, websocket
        - id: iot-bridge-service
          uri: lb://iot-bridge-service
          predicates:
            - Path=/v1/iot-bridge/**
          metadata:
            cors:
              allowedOrigins: "http://localhost:3333"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"

        - id: iot-core-service
          uri: lb://iot-core-service
          predicates:
            - Path=/v1/iot-core/**
          metadata:
            cors:
              allowedOrigins: "http://localhost:3333"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"


        - id: iot-core-ws
          uri: lb://iot-core-service
          predicates:
            - Path=/ws/**
            - Header=Upgrade, websocket

        - id: iot-user-service
          uri: lb://iot-user-service
          predicates:
            - Path=/v1/iot-user/**
          metadata:
            cors:
              allowedOrigins: "http://localhost:3333"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders: "*"

      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://iot-discovery-service:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    circuit-breakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

resilience4j:
  circuit-breaker:
    instances:
      iot-bridge-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
      iot-core-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
      iot-user-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
  retry:
    instances:
      iot-bridge-service:
        maxAttempts: 3
        waitDuration: 1s
      iot-core-service:
        maxAttempts: 3
        waitDuration: 1s
      iot-user-service:
        maxAttempts: 3
        waitDuration: 1s
  time-limiter:
    instances:
      iot-bridge-service:
        timeoutDuration: 5s
        cancelRunningFuture: true
      iot-user-service:
        timeoutDuration: 5s
        cancelRunningFuture: true

