server:
  port: 8001
  error:
    include-message: always
  netty:
    connection-timeout: 6000
    response-timeout: 6000
    max-connections: 1000

spring:
  application:
    name: iot-bridge-service
  main:
    web-application-type: reactive
  kafka:
    bootstrap-servers: kafka-service:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ro.upb.iotbridgeservice.kafka.serializer.MeasurementMessageSerializer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://iot-discovery-service:8761/eureka}
    registry-fetch-interval-seconds: 30
  instance:
    prefer-ip-address: true

cache:
  caffeine:
    initialCapacity: 100
    maximumSize: 500
    expireAfterWriteMinutes: 60
    weakKeys: true
    recordStats: true

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
