apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-influxdb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: influxdb
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80