apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-iot-user-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iot-user-service
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80