apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-iot-bridge-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iot-core-service
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80