/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ro.upb.common.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MeasurementMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6693415167482386267L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MeasurementMessage\",\"namespace\":\"ro.upb.common.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"measurement\",\"type\":\"string\"},{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"value\",\"type\":\"double\"},{\"name\":\"unit\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MeasurementMessage> ENCODER =
      new BinaryMessageEncoder<MeasurementMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MeasurementMessage> DECODER =
      new BinaryMessageDecoder<MeasurementMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MeasurementMessage> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MeasurementMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MeasurementMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MeasurementMessage>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MeasurementMessage to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MeasurementMessage from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MeasurementMessage instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MeasurementMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence id;
  private java.lang.CharSequence measurement;
  private java.lang.CharSequence userId;
  private double value;
  private java.lang.CharSequence unit;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MeasurementMessage() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param measurement The new value for measurement
   * @param userId The new value for userId
   * @param value The new value for value
   * @param unit The new value for unit
   */
  public MeasurementMessage(java.lang.CharSequence id, java.lang.CharSequence measurement, java.lang.CharSequence userId, java.lang.Double value, java.lang.CharSequence unit) {
    this.id = id;
    this.measurement = measurement;
    this.userId = userId;
    this.value = value;
    this.unit = unit;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return measurement;
    case 2: return userId;
    case 3: return value;
    case 4: return unit;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: measurement = (java.lang.CharSequence)value$; break;
    case 2: userId = (java.lang.CharSequence)value$; break;
    case 3: value = (java.lang.Double)value$; break;
    case 4: unit = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'measurement' field.
   * @return The value of the 'measurement' field.
   */
  public java.lang.CharSequence getMeasurement() {
    return measurement;
  }


  /**
   * Sets the value of the 'measurement' field.
   * @param value the value to set.
   */
  public void setMeasurement(java.lang.CharSequence value) {
    this.measurement = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public double getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(double value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'unit' field.
   * @return The value of the 'unit' field.
   */
  public java.lang.CharSequence getUnit() {
    return unit;
  }


  /**
   * Sets the value of the 'unit' field.
   * @param value the value to set.
   */
  public void setUnit(java.lang.CharSequence value) {
    this.unit = value;
  }

  /**
   * Creates a new MeasurementMessage RecordBuilder.
   * @return A new MeasurementMessage RecordBuilder
   */
  public static ro.upb.common.avro.MeasurementMessage.Builder newBuilder() {
    return new ro.upb.common.avro.MeasurementMessage.Builder();
  }

  /**
   * Creates a new MeasurementMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MeasurementMessage RecordBuilder
   */
  public static ro.upb.common.avro.MeasurementMessage.Builder newBuilder(ro.upb.common.avro.MeasurementMessage.Builder other) {
    if (other == null) {
      return new ro.upb.common.avro.MeasurementMessage.Builder();
    } else {
      return new ro.upb.common.avro.MeasurementMessage.Builder(other);
    }
  }

  /**
   * Creates a new MeasurementMessage RecordBuilder by copying an existing MeasurementMessage instance.
   * @param other The existing instance to copy.
   * @return A new MeasurementMessage RecordBuilder
   */
  public static ro.upb.common.avro.MeasurementMessage.Builder newBuilder(ro.upb.common.avro.MeasurementMessage other) {
    if (other == null) {
      return new ro.upb.common.avro.MeasurementMessage.Builder();
    } else {
      return new ro.upb.common.avro.MeasurementMessage.Builder(other);
    }
  }

  /**
   * RecordBuilder for MeasurementMessage instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MeasurementMessage>
    implements org.apache.avro.data.RecordBuilder<MeasurementMessage> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence measurement;
    private java.lang.CharSequence userId;
    private double value;
    private java.lang.CharSequence unit;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ro.upb.common.avro.MeasurementMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.measurement)) {
        this.measurement = data().deepCopy(fields()[1].schema(), other.measurement);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.unit)) {
        this.unit = data().deepCopy(fields()[4].schema(), other.unit);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
    }

    /**
     * Creates a Builder by copying an existing MeasurementMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(ro.upb.common.avro.MeasurementMessage other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.measurement)) {
        this.measurement = data().deepCopy(fields()[1].schema(), other.measurement);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.userId)) {
        this.userId = data().deepCopy(fields()[2].schema(), other.userId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.value)) {
        this.value = data().deepCopy(fields()[3].schema(), other.value);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.unit)) {
        this.unit = data().deepCopy(fields()[4].schema(), other.unit);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'measurement' field.
      * @return The value.
      */
    public java.lang.CharSequence getMeasurement() {
      return measurement;
    }


    /**
      * Sets the value of the 'measurement' field.
      * @param value The value of 'measurement'.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder setMeasurement(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.measurement = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'measurement' field has been set.
      * @return True if the 'measurement' field has been set, false otherwise.
      */
    public boolean hasMeasurement() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'measurement' field.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder clearMeasurement() {
      measurement = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.userId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public double getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder setValue(double value) {
      validate(fields()[3], value);
      this.value = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder clearValue() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'unit' field.
      * @return The value.
      */
    public java.lang.CharSequence getUnit() {
      return unit;
    }


    /**
      * Sets the value of the 'unit' field.
      * @param value The value of 'unit'.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder setUnit(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.unit = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'unit' field has been set.
      * @return True if the 'unit' field has been set, false otherwise.
      */
    public boolean hasUnit() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'unit' field.
      * @return This builder.
      */
    public ro.upb.common.avro.MeasurementMessage.Builder clearUnit() {
      unit = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MeasurementMessage build() {
      try {
        MeasurementMessage record = new MeasurementMessage();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.measurement = fieldSetFlags()[1] ? this.measurement : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.userId = fieldSetFlags()[2] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.value = fieldSetFlags()[3] ? this.value : (java.lang.Double) defaultValue(fields()[3]);
        record.unit = fieldSetFlags()[4] ? this.unit : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MeasurementMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<MeasurementMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MeasurementMessage>
    READER$ = (org.apache.avro.io.DatumReader<MeasurementMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.measurement);

    out.writeString(this.userId);

    out.writeDouble(this.value);

    out.writeString(this.unit);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.measurement = in.readString(this.measurement instanceof Utf8 ? (Utf8)this.measurement : null);

      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.value = in.readDouble();

      this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);

    } else {
      for (int i = 0; i < 5; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.measurement = in.readString(this.measurement instanceof Utf8 ? (Utf8)this.measurement : null);
          break;

        case 2:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 3:
          this.value = in.readDouble();
          break;

        case 4:
          this.unit = in.readString(this.unit instanceof Utf8 ? (Utf8)this.unit : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










