{
 "title": "Kafka Metrics",
 "description": "spring-kafka metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "topic",
    "query": "label_values(kafka_consumer_fetch_manager_records_lead, topic)"
   },
   {
    "name": "client_id",
    "label": "client_id",
    "query": "label_values(kafka_consumer_fetch_manager_records_lead{topic=\"$topic\"},client_id)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(kafka_consumer_connection_close_rate{client_id=~\"$client_id\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Producer Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_send_total[1m])\n",
     "legendFormat": "Consumer Throughput"
    }
   ]
  },
  {
   "title": "In Flight Messages",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_in_flight_messages", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Messages Sent",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_record_send_total\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_request_latency_avg",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Error Rate Panel",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(kafka_producer_record_error_total / kafka_producer_record_send_total) * 100\n",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "Available Buffer Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_buffer_available_bytes\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Compression Ratio",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(kafka_compression_ratio)", "legendFormat": "ratio" }
   ]
  },
  {
   "title": " Message Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_producer_record_size_avg", "legendFormat": "Avg record size" },
    { "expr": "kafka_producer_record_size_max", "legendFormat": "Max record size" }
   ]
  },
  {
   "title": "Batch Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kafka_producer_batch_size_avg", "legendFormat": "Avg Batch Size (bytes)" },
    { "expr": "kafka_producer_batch_size_max", "legendFormat": "Max Batch Size " }
   ]
  },
  {
   "title": "Retries",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_producer_record_retry_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retry Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 5, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(kafka_producer_record_retry_total[1m])\n",
     "legendFormat": "Retry Rate (retries/sec)"
    }
   ]
  },
  { "title": "Consumer ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "AVG Commit Latency",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(kafka_consumer_coordinator_commit_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"})"
    }
   ]
  },
  {
   "title": "Total lag ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_fetch_manager_records_lag{instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Commit Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "commit/sec" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_commit_rate{instance=~\"$instance\", client_id=~\"$client_id\"})"
    }
   ]
  },
  {
   "title": "Join Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_coordinator_join_rate{instance=~\"$instance\", client_id=~\"$client_id\"})"
    }
   ]
  },
  {
   "title": "Consumer Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_rate{instance=~\"$instance\", topic=~\"$topic\"}\n",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Consumed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_bytes_consumed_rate{instance=~\"$instance\", topic=~\"$topic\"}\n",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Messages Consumed by Topic",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_consumed_total{instance=~\"$instance\", topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Duplicated Messages",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_consumer_messages_duplicate_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumption lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_lag{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}",
     "legendFormat": "consumer lag - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    }
   ]
  },
  {
   "title": "Fetch latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch avg - {{instance}} - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_fetch_latency_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch max - {{instance}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "Fetch rate",
   "type": "timeseries",
   "description": "Measures the rate at which a Kafka consumer is making fetch requests to the Kafka brokers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
     "legendFormat": "instance - {{instance}} | client-id - {{client_id}}"
    }
   ]
  },
  {
   "title": "Consumed Bytes rate",
   "type": "timeseries",
   "description": "Monitor the rate at which Kafka consumers are consuming bytes from the Kafka brokers",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(kafka_consumer_fetch_manager_bytes_consumed_rate{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}[5m])",
     "legendFormat": "consumption bytes - {{instance}} - {{client_id}} - {{topic}}"
    }
   ]
  },
  {
   "title": "Fetch Throttle",
   "type": "timeseries",
   "description": "Measures the average fetch throttle time for Kafka consumers. The throttle time refers to the time the consumer spends waiting due to throttling enforced by Kafka brokers.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch avg - {{instance}} - {{client_id}}"
    },
    {
     "expr": "kafka_consumer_fetch_manager_fetch_throttle_time_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
     "legendFormat": "fetch max - {{instance}} - {{client_id}}"
    }
   ]
  },
  {
   "title": "Records per request",
   "type": "timeseries",
   "description": "Measures the average number of records that a Kafka consumer fetches per request from Kafka brokers",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "kafka_consumer_fetch_manager_records_per_request_avg{ instance=~\"$instance\", client_id=~\"$client_id\", topic=~\"$topic\"}",
     "legendFormat": "records avg - {{instance}} | client-id -{{client_id}} | topic - {{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "assigned partitions",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_assigned_partitions{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "assigned - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "commit latency",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_commit_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "commit avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_commit_latency_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "commit max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "speed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_commit_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
       "legendFormat": "commit rate - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_join_rate{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "join rate - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_heartbeat_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
       "legendFormat": "heartbeat rate - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_sync_rate{instance=~\"$instance\", client_id=~\"$client_id\"} ",
       "legendFormat": "sync rate - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "join time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_join_time_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "join avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_join_time_max{instance=~\"$instance\", client_id=~\"$client_id\"}\n",
       "legendFormat": "join max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "last heartbeat ago",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_last_heartbeat_seconds_ago{ instance=~\"$instance\", client_id=~\"$client_id\"} ",
       "legendFormat": "heartbeat ago - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "sync time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_sync_time_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "sync avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_sync_time_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "sync max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "rebalance latency ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_rebalance_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_rebalance_latency_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "rebalance total ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_rebalance_total{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance total - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_failed_rebalance_total{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance failed total - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "rebalance rate per hour",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_rebalance_rate_per_hour{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance per hour - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_failed_rebalance_rate_per_hour{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "rebalance failed per - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "last rebalance ago",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_last_rebalance_seconds_ago{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "last rebalance - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "partition assigned / revoked latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_consumer_coordinator_partition_assigned_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "assigned avg - {{instance}} | client-id - {{client_id}}"
      },
      {
       "expr": "kafka_consumer_coordinator_partition_revoked_latency_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "revoked avg - {{instance}} | client-id - {{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Global Connection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "io wait ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "kafka_consumer_io_wait_ratio{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "io wair ratio - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "io ratio",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "kafka_consumer_io_ratio{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "io ratio - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "io time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
     "targets": [
      {
       "expr": "kafka_consumer_io_time_ns_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "io time  - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "io wait time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
     "targets": [
      {
       "expr": "kafka_consumer_io_wait_time_ns_avg{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "io wait time  - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "select rate",
     "type": "timeseries",
     "description": "Number of times the I/O layer checked for new I/O to perform per second.\n",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 101 },
     "targets": [
      {
       "expr": "kafka_consumer_select_rate{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "select rate  - {{instance}} | client-id - {{client_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Per-Broker Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "incoming / outgoing bytes rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 82 },
     "targets": [
      {
       "expr": "kafka_consumer_incoming_byte_rate{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "incoming - {{instance}} | client-id - {{client_id}} - {{topic}}"
      },
      {
       "expr": "kafka_consumer_outgoing_byte_rate{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "outgoing - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "request size",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 82 },
     "targets": [
      {
       "expr": "kafka_consumer_request_size_avg{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "request avg - {{instance}} | client-id - {{client_id}} - {{topic}}"
      },
      {
       "expr": "kafka_consumer_request_size_max{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "request max - {{instance}} | client-id - {{client_id}}"
      }
     ]
    },
    {
     "title": "request / response",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 93 },
     "targets": [
      {
       "expr": "kafka_consumer_node_request_rate{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "request rate - {{instance}} | client-id - {{client_id}} | node {{node_id}}"
      },
      {
       "expr": "kafka_consumer_node_response_rate{instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "response rate - {{instance}} | client-id - {{client_id}} | node {{node_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Poll metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "collapsed": true,
   "panels": [
    {
     "title": "time between poll ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_consumer_time_between_poll_avg{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "time between poll avg {{instance}}"
      },
      {
       "expr": "kafka_consumer_time_between_poll_max{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "time between poll max {{instance}}"
      }
     ]
    },
    {
     "title": "Last poll ago",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_consumer_last_poll_seconds_ago{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "last poll ago {{instance}}"
      }
     ]
    },
    {
     "title": "poll idle time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "kafka_consumer_poll_idle_ratio_avg{ instance=~\"$instance\", client_id=~\"$client_id\"}",
       "legendFormat": "time idle {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}