name: Build & Push

on:
  push:
    branches: [deploy]
  workflow_dispatch:

jobs:
  publish:
    name: Publish Iot-Commons to GitHub Package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Deploy to GitHub
        run: mvn --batch-mode -DuseGitHubPackages=true deploy --file iot-commons/pom.xml
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_GITHUB_TOKEN }}

  build_and_push:
    name: Build & Push to DockerHub
    needs: publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [iot-core-service, iot-discovery-service, iot-bridge-service, iot-gateway-service, iot-user-service]  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('${{ matrix.service }}/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Set up Maven settings
        uses: s4u/maven-settings-action@v2.5.0
        with:
          servers: '[{"id": "github","configuration": {"httpHeaders": {"property": {"name": "Authorization","value": "Bearer ${{ secrets.DEPLOY_GITHUB_TOKEN }}"}}}}]'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file ${{ matrix.service }}/pom.xml

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Build and Push to DockerHub
        run: |
          cd ${{ matrix.service }}
          docker build -t alexdragnea/disertatie-${{ matrix.service }}:latest .
          docker push alexdragnea/disertatie-${{ matrix.service }}:latest

  owasp:
    needs: build_and_push
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Pull All Docker Images
        run: |
          docker pull alexdragnea/disertatie-iot-core-service:latest
          docker pull alexdragnea/disertatie-iot-discovery-service:latest
          docker pull alexdragnea/disertatie-iot-bridge-service:latest
          docker pull alexdragnea/disertatie-iot-gateway-service:latest
          docker pull alexdragnea/disertatie-iot-user-service:latest

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: LS
        run: |
          ls

      - name: Start All Services
        run: |
          docker-compose up -d  # This will start all services defined in docker-compose.yml

      # Run OWASP ZAP scan targeting each service on its specific port
      - name: Run OWASP ZAP Baseline Scans
        run: |
          services=( 
            "iot-core-service:8002" 
            "iot-bridge-service:8001" 
            "iot-user-service:8003" 
          )
          for service in "${services[@]}"; do
            IFS=":" read -r name port <<< "$service"
            echo "Running OWASP ZAP scan on $name at port $port"
            docker run --network="host" zaproxy/zap2docker-stable zap-baseline.py -t http://localhost:$port -r zap_report_$name.html
          done

      - name: Shut down all containers
        run: docker-compose down  # Ensure containers are stopped after testing
